/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HandImport } from './routes/hand'
import { Route as AbsImport } from './routes/abs'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const HandRoute = HandImport.update({
  path: '/hand',
  getParentRoute: () => rootRoute,
} as any)

const AbsRoute = AbsImport.update({
  path: '/abs',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/abs': {
      id: '/abs'
      path: '/abs'
      fullPath: '/abs'
      preLoaderRoute: typeof AbsImport
      parentRoute: typeof rootRoute
    }
    '/hand': {
      id: '/hand'
      path: '/hand'
      fullPath: '/hand'
      preLoaderRoute: typeof HandImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abs': typeof AbsRoute
  '/hand': typeof HandRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abs': typeof AbsRoute
  '/hand': typeof HandRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/abs': typeof AbsRoute
  '/hand': typeof HandRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abs' | '/hand'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abs' | '/hand'
  id: '__root__' | '/' | '/abs' | '/hand'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbsRoute: typeof AbsRoute
  HandRoute: typeof HandRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbsRoute: AbsRoute,
  HandRoute: HandRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/abs",
        "/hand"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/abs": {
      "filePath": "abs.tsx"
    },
    "/hand": {
      "filePath": "hand.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
